# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'olincollege.github.io'
baseurl: '/ClashofTanks'
title: 'ClashofTanks Team'
description: 'Remaking the classic Atari tank game in Python.'
permalink: pretty
logo: "/assets/Tank1.png"
email: "sidneyt27@gmail.com"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Install
  url: /getting-started/
- title: How to play
  url: /how-to/
- title: Bug fixes
  url: /blog/
- title: Report a bug
  url: /bugs/
- title: About
  url: /about/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "A collection of all bugs found and addressed so far."
    feature_text: |
      Known bugs
    feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
